### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by 91320113** [wzkres/pve-ddns-client#1]
Hello,
Could you please provide a how to install on Debian / Ubuntu apt?
Not sure how to start using it?

Thanks

**Comment by wzkres** [comment]
Hi @91320113,

Sorry, there is currently no apt package, just grab the prebuilt Linux artifact from GitHub Actions page, extract the zip, edit the yaml config file, then run the program like this:

> ./pve-ddns-client -c ./pve-ddns-client.yml

Also, you can create a simple service to run the program at system startup, systemd or supervisor is good enough.


Regards

**Comment by 91320113** [comment]
Thank you, waiting for the builds to complete in the github actions, it was showing expired before.

how to build without github actions like directly on my server?

**Comment by 91320113** [comment]
https://github.com/wzkres/pve-ddns-client/actions/runs/7245121795/job/19734565520
Error: Process completed with exit code 2.

The build failed.

**Comment by wzkres** [comment]
I just made some changes to the building script, it is ok now.

Linux artifact was built on Ubuntu 20.04, so if your server runs versions prior to that, there may be C++ standard library compatibility issues. If so, you will need to build the program yourself, install cmake and follow the instructions in this workflow file: https://github.com/wzkres/pve-ddns-client/blob/main/.github/workflows/cmake.yml

**Comment by rabinassar** [comment]
Thank you so much

**Comment by 91320113** [comment]
Thank you so much

**Comment by wzkres** [comment]
You're welcome.
